default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:

production:
  <<: *default
  database: web_production
  username: web_p
  password: <%= ENV["WEB_P_PASSWORD"] %>

staging:
  <<: *default
  database: web_staging
  username: web_s
  password: <%= ENV["WEB_S_PASSWORD"] %>

development:
  <<: *default
  database: web_development

test:
  <<: *default
  database: web_test
