default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:

production:
  <<: *default
  database: web_production
  username: web_p
  password: yA6PGwdyMCHab8xfZgHs

development:
  <<: *default
  database: web_development

test:
  <<: *default
  database: web_test
