default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

production:
  <<: *default
  database: web
  username: web_p
  password: yA6PGwdyMCHab8xfZgHs
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: web_development

test:
  <<: *default
  database: web_test
